### ISSUE TITLE
how to run it with cuda-9.2?

### ISSUE THREAD

**Issue by threefoldo** [luanyi/DyGIE#2]
Thank you for this program, it's really helpful.

I have upgrade the nvidia driver to cuda-9.2 long ago which is not supported by tensorflow 1.8. Is it possible to run these programs with newer tensorflow? I guess tensorflow 2.0 and python3 will be better than current version.

And there is a missing file 'scripts/get_char_vocab.py'. Not sure what it does though.

**Comment by threefoldo** [comment]
I have managed to run it with tensorflow 1.8, found several minor errors:

1. spelling error in experiments.conf
  genia_bast_ner => genia_best_ner

2. CUDA_VISIBLE_DEVICES in utils.py
  it's better to use the environ variable if it was set already.

**Comment by luanyi** [comment]
Fixed the typo. Thanks! We don't have a python3 and Tensorflow 2.0 version yet. But we will release a pytorch version that can replicate the results soon. Will keep you posted.

**Comment by threefoldo** [comment]
Thanks.
