### ISSUE TITLE
Is this project active? Does it work? 

### ISSUE THREAD

**Issue by urialon** [luanyi/DyGIE#8]
Hi @luanyi ,
Thank you for sharing this project. The paper is very interesting and the results are impressive.
 
I am trying to follow the README just to reproduce the results from the paper, but there are many errors and mistakes.
I am fixing some of them, but others always pop up.
Most issues are related to incorrect data paths.

I see that others experience similar issues and are usually not getting any responses. 
So - is this project active and maintained? Can I ask more questions about running, training, etc?

Thanks!
Uri

**Comment by yangxia605** [comment]
i  have the same confusion.

**Comment by yangxia605** [comment]
run like this "python evaluator.py wlp_best_relation",the parameter after evaluator.py in the "model1/experiment.conf",you can choose what you want. 
hope i will help you.

**Comment by luanyi** [comment]
Yes it's active. Please post your issues I'll reply as soon as possible. Alternatively, we have another repo https://github.com/dwadden/dygiepp which is an improved version that uses BERT. You can try that out as well.
